application: ueuno1
version: 1
runtime: go
api_version: 2

handlers:
- url: /(.+\.(css|gif|ico|jpg|js|png))
  static_files: static/\1
  upload: static/(.+\.(css|gif|ico|jpg|js|png))

- url: .*
  script: _go_app
