application: ueuno1
version: 1-5
runtime: go
api_version: 3

handlers:
- url: /(.+\.(css|gif|html|ico|jpg|js|png|txt))
  static_files: static/\1
  upload: static/(.+\.(css|gif|html|ico|jpg|js|png|txt))

- url: .*
  script: _go_app
